from setuptools import setup, find_packages

setup(
    name="aclimate_resampling",
    version='v1.0.0',
    author="stevensotelo",
    author_email="h.sotelo@cgiar.com",
    description="Resampling module",
    url="https://github.com/victor-993/aclimate_resampling",
    download_url="https://github.com/victor-993/aclimate_resampling",
    packages=find_packages('src'),
    package_dir={'': 'src'},
    keywords='resampling aclimate',
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
    install_requires=[
        "affine==2.4.0",
        "attrs==23.1.0",
        "cdsapi==0.6.1",
        "certifi==2023.5.7",
        "cftime==1.6.2",
        "charset-normalizer==3.2.0",
        "click==7.1.2",
        "click-plugins==1.1.1",
        "cligj==0.7.2",
        "colorama==0.4.6",
        "dpcpp-cpp-rt==2023.2.0",
        "GDAL==3.2.1",
        "idna==3.4",
        "intel-cmplr-lib-rt==2023.2.0",
        "intel-cmplr-lic-rt==2023.2.0",
        "intel-opencl-rt==2023.2.0",
        "intel-openmp==2023.2.0",
        "mkl==2023.2.0",
        "mkl-fft==1.3.1",
        "mkl-random==1.2.2",
        "mkl-service==2.4.0",
        "netCDF4==1.6.4",
        "numexpr==2.8.4",
        "numpy==1.22.4",
        "packaging==23.1",
        "pandas==2.0.3",
        "pyparsing==3.1.0",
        "pyproj==3.6.0",
        "python-dateutil==2.8.2",
        "pytz==2023.3",
        "rasterio==1.2.0",
        "requests==2.31.0",
        "rioxarray==0.14.1",
        "six==1.16.0",
        "snuggs==1.4.7",
        "tbb==2021.10.0",
        "tqdm==4.65.0",
        "tzdata==2023.3",
        "urllib3==2.0.3",
        "xarray==2023.7.0"
    ]
)